### ISSUE TITLE
Using Black for formatting

### ISSUE THREAD

**Issue by oulenz** [getpelican/cookiecutter-pelican-plugin#2]
I was wondering what your thoughts were behind including Black-enforced formatting. I wasn't familiar with it, but there are two design decisions in particular which I find questionable: the arbitrary line length of 88, and converting all single quotes to double quotes.

(I guess people could manually remove from or reconfigure Black in their newly created template, or would you consider that undesirable?)

**Comment by justinmayer** [comment]
Both of the two design decisions you mentioned are almost always the contentious ones that come up in discussions about Black. While I personally don't have strong feeling about them either way, it's clear that some folks do, and I respect that.

At the same time, what I've come to realize about Black, particularly regarding why it has become so popular, is that its value comes from _making a decision_. Even in my own projects, I've found countless examples of when I have used single-quotes in one file and double-quotes in another. Or even inconsistency _in the same file_. It's madness. The genius of code auto-formatting is the application of a single consistent standard, even when that standard isn't precisely what everyone thinks it should be. The benefits of the standardization outweigh the merits of being able to, for example, choose single vs. double-quotes.

So my preference would be that we adhere to and apply this standard wherever we can, reaping the consistency benefits along the way.

**Comment by oulenz** [comment]
I appreciate the value of consistency, but I'm not bothered if things are only approximately consistent. I don't really see the point of being stricter than PEP8.

(I find it ironic that while the professed purpose of Black is to enforce consistency, they do this by deviating from the PEP8 line length. That's just inconsistent. Also, my impression (which may be flawed) is that single quotes are more widespread than double quotes on e.g. string parameters.)

I guess a question for us is whether we want to enforce stylistic consistency across plugins, or whether it's ok if individual authors are consistent within their own plugin.

**Comment by justinmayer** [comment]
Regarding consistency, I have had a different experience. I find mixed single- vs. double-quotation mark usage to be jarring and **really** value having that automatically sorted out. Similarly, having code indented one way here and another way there, seeing indent changes in pull requests… This is all just wasted noise, time, and effort, and I'm deliriously glad to have that all automatically disappear. And that's just on the code reading/parsing side of things. In addition to that, there's the time we have all collectively spent wondering how and where to indent code, just to pick one example, and I'm all for removing that burden. The consistency is largely a nice side effect.

I'm not sure whether single-quote style is more widespread than double-quote style, but I very much agree with [Black's rationale for standardizing on double-quotes](https://github.com/psf/black#strings).

I don't think Black's choice of deviating from PEP8's line length is inconsistent. One can disagree with that choice, but at least Black is _internally_ consistent. Having seen the kinds of code-formatting contortions that are often necessary to get code to fit within 79-character line limits, and the resulting readability sacrifices that must be made to achieve that, I can appreciate why Black chose a slightly longer line length, and thus I'm in favor of that choice.

If a plugin author strongly disagrees with Black's standardized line length and feels it is really important to them that their plugin adhere to PEP8's 79-character limit, I think they are welcome to [configure Black](https://github.com/psf/black#line-length) and [Flake8](https://github.com/getpelican/cookiecutter-pelican-plugin/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/tox.ini#L2) accordingly. Otherwise, I think it would be beneficial to the community to conform to a unified standard. But that's just my opinion, of course. 😊

**Comment by oulenz** [comment]
I can live with using Black in the CookieCutter template, if we acknowledge that since plugins are outside contributions, we should be open to their authors having different code style preferences.

(FWIW, I personally don't believe in hard line length limits, and almost exclusively use single quotes.)

**Comment by avaris** [comment]
I didn't use Black before, but from what I understand the point is: it will do conversions *for you* automatically. So having Black set as `"` instead of `'` has no effect on how you write code. You can still use `'` and at the end it will be transformed into `"` without any additional input from you. I think the widespread use of `'` over `"` is because it's easier to type them in certain keyboard layouts (e.g. US). 

Regarding line limits, my personal usage is somewhat in line with Black. I usually setup two rulers in my editor: `80` and `90`. `80` is soft limit and `90` is hard limit. I try to stay in `80` if possible but I don't fret too much if it exceeds by a few characters.

**Comment by oulenz** [comment]
> I didn't use Black before, but from what I understand the point is: it will do conversions _for you_ automatically. So having Black set as `"` instead of `'` has no effect on how you write code. You can still use `'` and at the end it will be transformed into `"` without any additional input from you.

Sure, but if you use it like it that it seems to me that you end up working with code that looks jarring to you all the time.

The more important point is that while it's an excellent idea to recommend a certain workflow for people who wouldn't otherwise know how to start out, I don't think we can or should force people who want to contribute a plugin. I mean I understand that shared standards are necessary when a large group of people is working on the same codebase, but when it's plugins which will mostly see contributions by a single person, I think that we risk alienating potential contributors if we stipulate a specific workflow using a specific toolchain that probably does not match theirs.

> I think the widespread use of `'` over `"` is because it's easier to type them in certain keyboard layouts (e.g. US).

(I know for me it's because I programmed in SQL before, which only allows single quotes.)

**Comment by justinmayer** [comment]
> I mean I understand that shared standards are necessary when a large group of people is working on the same codebase […]

Part of the reason for consolidating the plugins under a single organization is to make it easier for folks to contribute, including members of the Pelican dev team. That way plugins will hopefully be maintained better over the long term.

> […] when it's plugins which will mostly see contributions by a single person […]

I think there are actually quite a few plugins with numerous contributors — not just a single person.

As I explained previously, the intention is for these conventions to serve as strong recommendations. If someone voices strenuous opposition to a particular standard, then the corresponding configuration files can be modified to support their preference.

**Comment by justinmayer** [comment]
@oulenz: Does my response above seem reasonable enough to bring this to a close? 😊

**Comment by oulenz** [comment]
> ...consolidating the plugins under a single organization...

I think one reason why we see this differently is because I understood this process we're in not as a consolidation, but rather as the opposite. Plugins were already under a single organisation, in fact they were in a single repo, with one set of maintainers. Now, each plugin has its own repo, with its own maintainers. I think it is a good thing that this allows people to support a specific plugin they wrote and that it spreads out responsibility.

But I'm happy with your answer, sorry for letting this linger!

**Comment by justinmayer** [comment]
> I understood this process we're in not as a consolidation, but rather as the opposite.

Agreed — I don't view it as a consolidation at all. In fact, from the beginning I've tried to frame it as more of a collaborative [Jazzband](jazzband.co)-style collective endeavor.

> I think it is a good thing that this allows people to support a specific plugin they wrote and that it spreads out responsibility.

Absolutely. Fully agree. 😁
