### ISSUE TITLE
Potential limitation with using poetry

### ISSUE THREAD

**Issue by Lucas-C** [getpelican/cookiecutter-pelican-plugin#8]
Hi.

I see you choosed to use `poetry` in this cookiecutter template, instead of for example a `setup.cfg` or `setup.py` file.

I see one current limitation with this: we need to install Pelican in editable mode in order to access its `tests` package:  `pip install -e git+https://github.com/getpelican/pelican.git#egg=pelican`

If I'm not wrong, someone currently using your template won't be able to do use the following in their tests code:
```python
from pelican.tests.support import get_settings, unittest
```

Because `poetry` does not support declaring `dev-dependencies` in editable mode, I think one will still need to use a `dev-requirements.txt` file for their Pelican plugins.

**Comment by davidag** [comment]
Hi @Lucas-C !

A [related issue](https://github.com/getpelican/cookiecutter-pelican-plugin/issues/3) was reported some time ago after facing this very same issue in the [feed-filter plugin](https://github.com/pelican-plugins/feed-filter).

The conclusion was that the current cookiecutter template works just fine if you follow the contributing guidelines to the letter.

**Comment by Lucas-C** [comment]
Ok, thanks @davidag, closing this then

**Comment by justinmayer** [comment]
Hi Lucas. There are a few reasons for the current state of affairs, which I will talk about in no particular order, mainly as a way to document for my own sanity the long cognitive path I took to arrive where we are now:

* Poetry is meant for dependency management and does not support one-off installation commands like: `poetry install ~/Projects/pelican`
* Poetry lacks a command to _only_ install development dependencies.
* Pip cannot install `pyproject.toml`-based projects in editable mode (`setup.py` is required).
* Pelican cannot include its tests in the source tarball without breaking installation on Windows.

The first two situations are very unlikely to change. The third and fourth, on the other hand, could change in the future. For example, note the use of the word "currently" in the Pip error message (emphasis mine):
> A "pyproject.toml" file was found, but editable mode _currently_ requires a setup.py based build.

I considered several workarounds before settling on the current solution, which as @davidag mentioned, is Pip-installing Pelican in editable mode before running `poetry install`. Let's look at some other potential solutions, and why I decided they don't currently work. For example, you said:

> Because Poetry does not support declaring dev-dependencies in editable mode […]

Actually, Poetry **does** support this, at least in recent versions. If your clone of Pelican core is in `~/Projects/pelican/`, and your current directory is your plugin clone at, say, `~/Projects/pelican-plugins/linkbacks/`, you could do this:

    poetry add --dev ../../pelican

Doing so would add the following line to your development dependencies in `pyproject.toml`:

    pelican = {path = "../../pelican"}

Yay! But that only helps if Pelican is not listed as a regular (non-dev) dependency. Since regular dependencies are installed first, the above development dependency will be ignored once Poetry realizes that Pelican is already installed. 🤦‍♂ 

If Poetry had a command to _only_ install development dependencies (which it doesn't), that could be run first, followed by a regular `poetry install` invocation, resulting in Pelican core installed first in editable mode.

I considered removing Pelican from the list of regular dependencies in order to work around this situation, but then anyone who wants to `poetry install` the plugin must first clone the Pelican core source in the exact right path location, even if they have no need to modify Pelican core's source at all (and therefore have no need to install Pelican in editable mode).

Of course, another solution would be to bundle `setup.py` files everywhere, but that seemed like a messy solution to a problem that should really be solved in a neater, cleaner manner. Relying on Pelican core's `setup.py` file, and the ability to install it in editable mode with Pip before doing anything else, seemed like the least messy way to solve this problem for now, and that's why I documented the "Setting Up Your Development Environment" steps that way.

Ultimately, I am hoping that this situation can be more fully resolved by being able to [include the tests in Pelican's source tarball](https://github.com/getpelican/pelican/issues/2635). There is a [PR that might fix that](https://github.com/pypa/pip/pull/7138), which I hope is merged and released soon.

**Comment by Lucas-C** [comment]
Thanks for the detailed answer :)
