### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by thecaligarmo** [getpelican/cookiecutter-pelican-plugin#9]
Hey, I followed the instructions on [https://docs.getpelican.com/en/latest/contribute.html#setting-up-the-development-environment](the docs) to the T, and I still got the following error when running `pytest`

```
    from pelican.tests.support import get_context, get_settings
E   ModuleNotFoundError: No module named 'pelican.tests'
```
I think it refers to an issue already presented before:
[https://github.com/getpelican/cookiecutter-pelican-plugin/issues/3](https://github.com/getpelican/cookiecutter-pelican-plugin/issues/3)

I noticed that the documentation was asking people to run the following code:
```
pip install -e ~/projects/pelican invoke
invoke setup
```
The problem is that invoke setup was reinstalling pelican and so it was removing it from being editable. The only way I could get this to work was to reverse the order. (So run `pip install -e ~/projects/pelican` after I ran `invoke setup`.

Not sure if it's just my machine, but figured I'd warn.

**Comment by justinmayer** [comment]
It's not just on your workstation. I had seen the same thing recently, which I assume was caused by a change in Poetry's behavior. I have [updated the documentation](https://github.com/getpelican/pelican/commit/3b5cdef7f9193b5912d83c108874e0856ccc8fe8) appropriately to work around that change.

Thank you for the nudge to update the docs. Much appreciated! :sparkles:
